name = "election-night"
main = "index.js"
compatibility_date = "2024-01-01"

[triggers]
crons = [ "* * * * *" ]

[[kv_namespaces]]
binding = "ELECTION_RESULTS"
id = "db737acc9d624075bab261c60628f95c"
preview_id = "db737acc9d624075bab261c60628f95c"
