#!/usr/bin/env python3
"""
수집된 광역의원 데이터를 council_members.json으로 통합
────────────────────────────────────────
각 시도의회 웹사이트 + 나무위키에서 수집한 데이터를 TopoJSON 선거구명에 매칭
"""

import json
import re
from pathlib import Path
from datetime import datetime

BASE_DIR = Path(__file__).parent.parent
TOPO_DIR = BASE_DIR / 'data' / 'council'
OUTPUT_FILE = TOPO_DIR / 'council_members.json'

PARTY_KEY_MAP = {
    '더불어민주당': 'democratic',
    '민주당': 'democratic',
    '국민의힘': 'ppp',
    '조국혁신당': 'reform',
    '개혁신당': 'newReform',
    '진보당': 'progressive',
    '정의당': 'justice',
    '무소속': 'independent',
}

def normalize_party(name):
    return PARTY_KEY_MAP.get(name.strip(), 'other')

def load_topo_districts(region_key):
    topo_file = TOPO_DIR / f'council_districts_{region_key}_topo.json'
    if not topo_file.exists():
        return []
    with open(topo_file, encoding='utf-8') as f:
        topo = json.load(f)
    obj_key = list(topo['objects'].keys())[0]
    return [
        g['properties']['district_name']
        for g in topo['objects'][obj_key]['geometries']
        if 'district_name' in g.get('properties', {})
    ]

def normalize_district(name):
    """선거구명 정규화"""
    name = re.sub(r'\s+', ' ', name.strip())
    # "강남구1" → "강남구 제1선거구"
    m = re.match(r'^(.+?)(\d+)$', name)
    if m:
        name = f'{m.group(1)} 제{m.group(2)}선거구'
    # "종로구제1선거구" → "종로구 제1선거구"
    name = re.sub(r'(\S[구시군])(제?\d+선거구)', r'\1 \2', name)
    # "종로구 1선거구" → "종로구 제1선거구"
    name = re.sub(r'(\s)(\d+선거구)', r'\1제\2', name)
    return name

def match_district(api_name, topo_names):
    normalized = normalize_district(api_name)
    if normalized in topo_names:
        return normalized
    for tn in topo_names:
        if normalize_district(tn) == normalized:
            return tn
    # 부분 매칭
    m = re.match(r'(.+?)\s*제?(\d+)\s*선거구', normalized)
    if m:
        base, num = m.group(1), m.group(2)
        for tn in topo_names:
            if base in tn and f'제{num}선거구' in tn:
                return tn
    # 단일 선거구 (군위군 → 군위군 선거구)
    base = normalized.replace(' 선거구', '').strip()
    for tn in topo_names:
        if tn.startswith(base) and '선거구' in tn:
            return tn
    # "보은군" → "보은군 선거구"
    if not normalized.endswith('선거구'):
        candidate = normalized + ' 선거구'
        if candidate in topo_names:
            return candidate
    return None


# ── 수집된 데이터 ──
RAW_DATA = {
    'seoul': [
        {"name": "이새날", "party": "국민의힘", "district": "강남구 제1선거구"},
        {"name": "김형재", "party": "국민의힘", "district": "강남구 제2선거구"},
        {"name": "김현기", "party": "국민의힘", "district": "강남구 제3선거구"},
        {"name": "유만희", "party": "국민의힘", "district": "강남구 제4선거구"},
        {"name": "김동욱", "party": "국민의힘", "district": "강남구 제5선거구"},
        {"name": "김길영", "party": "국민의힘", "district": "강남구 제6선거구"},
        {"name": "김혜지", "party": "국민의힘", "district": "강동구 제1선거구"},
        {"name": "이종태", "party": "국민의힘", "district": "강동구 제2선거구"},
        {"name": "박춘선", "party": "국민의힘", "district": "강동구 제3선거구"},
        {"name": "장태용", "party": "국민의힘", "district": "강동구 제4선거구"},
        {"name": "김영철", "party": "국민의힘", "district": "강동구 제5선거구"},
        {"name": "이종환", "party": "국민의힘", "district": "강북구 제1선거구"},
        {"name": "이상훈", "party": "더불어민주당", "district": "강북구 제2선거구"},
        {"name": "이용균", "party": "더불어민주당", "district": "강북구 제3선거구"},
        {"name": "박수빈", "party": "더불어민주당", "district": "강북구 제4선거구"},
        {"name": "강석주", "party": "국민의힘", "district": "강서구 제2선거구"},
        {"name": "최진혁", "party": "국민의힘", "district": "강서구 제3선거구"},
        {"name": "김춘곤", "party": "국민의힘", "district": "강서구 제4선거구"},
        {"name": "김경훈", "party": "국민의힘", "district": "강서구 제5선거구"},
        {"name": "경기문", "party": "국민의힘", "district": "강서구 제6선거구"},
        {"name": "송도호", "party": "더불어민주당", "district": "관악구 제1선거구"},
        {"name": "왕정순", "party": "더불어민주당", "district": "관악구 제2선거구"},
        {"name": "임만균", "party": "더불어민주당", "district": "관악구 제3선거구"},
        {"name": "전병주", "party": "더불어민주당", "district": "광진구 제1선거구"},
        {"name": "박성연", "party": "국민의힘", "district": "광진구 제2선거구"},
        {"name": "김영옥", "party": "국민의힘", "district": "광진구 제3선거구"},
        {"name": "김혜영", "party": "국민의힘", "district": "광진구 제4선거구"},
        {"name": "서상열", "party": "국민의힘", "district": "구로구 제1선거구"},
        {"name": "김인제", "party": "더불어민주당", "district": "구로구 제2선거구"},
        {"name": "서호연", "party": "국민의힘", "district": "구로구 제3선거구"},
        {"name": "박칠성", "party": "더불어민주당", "district": "구로구 제4선거구"},
        {"name": "김성준", "party": "더불어민주당", "district": "금천구 제1선거구"},
        {"name": "최기찬", "party": "더불어민주당", "district": "금천구 제2선거구"},
        {"name": "신동원", "party": "국민의힘", "district": "노원구 제1선거구"},
        {"name": "오금란", "party": "더불어민주당", "district": "노원구 제2선거구"},
        {"name": "봉양순", "party": "더불어민주당", "district": "노원구 제3선거구"},
        {"name": "윤기섭", "party": "국민의힘", "district": "노원구 제5선거구"},
        {"name": "송재혁", "party": "더불어민주당", "district": "노원구 제6선거구"},
        {"name": "이경숙", "party": "국민의힘", "district": "도봉구 제1선거구"},
        {"name": "홍국표", "party": "국민의힘", "district": "도봉구 제2선거구"},
        {"name": "박석", "party": "국민의힘", "district": "도봉구 제3선거구"},
        {"name": "이은림", "party": "국민의힘", "district": "도봉구 제4선거구"},
        {"name": "이병윤", "party": "국민의힘", "district": "동대문구 제1선거구"},
        {"name": "심미경", "party": "국민의힘", "district": "동대문구 제2선거구"},
        {"name": "남궁역", "party": "국민의힘", "district": "동대문구 제3선거구"},
        {"name": "신복자", "party": "국민의힘", "district": "동대문구 제4선거구"},
        {"name": "이봉준", "party": "국민의힘", "district": "동작구 제1선거구"},
        {"name": "최민규", "party": "국민의힘", "district": "동작구 제2선거구"},
        {"name": "곽향기", "party": "국민의힘", "district": "동작구 제3선거구"},
        {"name": "이희원", "party": "국민의힘", "district": "동작구 제4선거구"},
        {"name": "이민석", "party": "국민의힘", "district": "마포구 제1선거구"},
        {"name": "소영철", "party": "국민의힘", "district": "마포구 제2선거구"},
        {"name": "김기덕", "party": "더불어민주당", "district": "마포구 제4선거구"},
        {"name": "정지웅", "party": "국민의힘", "district": "서대문구 제1선거구"},
        {"name": "문성호", "party": "국민의힘", "district": "서대문구 제2선거구"},
        {"name": "이승미", "party": "더불어민주당", "district": "서대문구 제3선거구"},
        {"name": "김용일", "party": "국민의힘", "district": "서대문구 제4선거구"},
        {"name": "박상혁", "party": "국민의힘", "district": "서초구 제1선거구"},
        {"name": "이숙자", "party": "국민의힘", "district": "서초구 제2선거구"},
        {"name": "고광민", "party": "국민의힘", "district": "서초구 제3선거구"},
        {"name": "최호정", "party": "국민의힘", "district": "서초구 제4선거구"},
        {"name": "박중화", "party": "국민의힘", "district": "성동구 제1선거구"},
        {"name": "구미경", "party": "국민의힘", "district": "성동구 제2선거구"},
        {"name": "이민옥", "party": "더불어민주당", "district": "성동구 제3선거구"},
        {"name": "황철규", "party": "국민의힘", "district": "성동구 제4선거구"},
        {"name": "한신", "party": "더불어민주당", "district": "성북구 제1선거구"},
        {"name": "김원중", "party": "국민의힘", "district": "성북구 제2선거구"},
        {"name": "강동길", "party": "더불어민주당", "district": "성북구 제3선거구"},
        {"name": "김태수", "party": "국민의힘", "district": "성북구 제4선거구"},
        {"name": "김규남", "party": "국민의힘", "district": "송파구 제1선거구"},
        {"name": "남창진", "party": "국민의힘", "district": "송파구 제2선거구"},
        {"name": "임춘대", "party": "국민의힘", "district": "송파구 제3선거구"},
        {"name": "이성배", "party": "국민의힘", "district": "송파구 제4선거구"},
        {"name": "유정인", "party": "국민의힘", "district": "송파구 제5선거구"},
        {"name": "김원태", "party": "국민의힘", "district": "송파구 제6선거구"},
        {"name": "채수지", "party": "국민의힘", "district": "양천구 제1선거구"},
        {"name": "허훈", "party": "국민의힘", "district": "양천구 제2선거구"},
        {"name": "우형찬", "party": "더불어민주당", "district": "양천구 제3선거구"},
        {"name": "이승복", "party": "국민의힘", "district": "양천구 제4선거구"},
        {"name": "김재진", "party": "국민의힘", "district": "영등포구 제1선거구"},
        {"name": "김종길", "party": "국민의힘", "district": "영등포구 제2선거구"},
        {"name": "도문열", "party": "국민의힘", "district": "영등포구 제3선거구"},
        {"name": "김지향", "party": "국민의힘", "district": "영등포구 제4선거구"},
        {"name": "김용호", "party": "국민의힘", "district": "용산구 제1선거구"},
        {"name": "최유희", "party": "국민의힘", "district": "용산구 제2선거구"},
        {"name": "성흠제", "party": "더불어민주당", "district": "은평구 제1선거구"},
        {"name": "이병도", "party": "더불어민주당", "district": "은평구 제2선거구"},
        {"name": "박유진", "party": "더불어민주당", "district": "은평구 제3선거구"},
        {"name": "정준호", "party": "더불어민주당", "district": "은평구 제4선거구"},
        {"name": "윤종복", "party": "국민의힘", "district": "종로구 제1선거구"},
        {"name": "임종국", "party": "더불어민주당", "district": "종로구 제2선거구"},
        {"name": "박영한", "party": "국민의힘", "district": "중구 제1선거구"},
        {"name": "이영실", "party": "더불어민주당", "district": "중랑구 제1선거구"},
        {"name": "임규호", "party": "더불어민주당", "district": "중랑구 제2선거구"},
        {"name": "박승진", "party": "더불어민주당", "district": "중랑구 제3선거구"},
        {"name": "민병주", "party": "국민의힘", "district": "중랑구 제4선거구"},
        {"name": "김경", "party": "더불어민주당", "district": "강서구 제1선거구"},
        {"name": "유정희", "party": "더불어민주당", "district": "관악구 제4선거구"},
        {"name": "서준오", "party": "더불어민주당", "district": "노원구 제4선거구"},
        {"name": "정진술", "party": "더불어민주당", "district": "마포구 제3선거구"},
        {"name": "옥재은", "party": "국민의힘", "district": "중구 제2선거구"},
    ],
    'busan': [
        {"name": "박종철", "party": "국민의힘", "district": "기장군 제1선거구"},
        {"name": "이승우", "party": "국민의힘", "district": "기장군 제2선거구"},
        {"name": "이준호", "party": "국민의힘", "district": "금정구 제2선거구"},
        {"name": "박대근", "party": "국민의힘", "district": "북구 제1선거구"},
        {"name": "김효정", "party": "국민의힘", "district": "북구 제2선거구"},
        {"name": "이종진", "party": "국민의힘", "district": "북구 제3선거구"},
        {"name": "박종율", "party": "국민의힘", "district": "북구 제4선거구"},
        {"name": "박철중", "party": "무소속", "district": "수영구 제1선거구"},
        {"name": "이승연", "party": "국민의힘", "district": "수영구 제2선거구"},
        {"name": "신정철", "party": "국민의힘", "district": "해운대구 제1선거구"},
        {"name": "임말숙", "party": "국민의힘", "district": "해운대구 제2선거구"},
        {"name": "김태효", "party": "국민의힘", "district": "해운대구 제3선거구"},
        {"name": "강무길", "party": "국민의힘", "district": "해운대구 제4선거구"},
        {"name": "송우현", "party": "국민의힘", "district": "동래구 제2선거구"},
        {"name": "서국보", "party": "국민의힘", "district": "동래구 제3선거구"},
        {"name": "안재권", "party": "국민의힘", "district": "연제구 제1선거구"},
        {"name": "김형철", "party": "국민의힘", "district": "연제구 제2선거구"},
        {"name": "박희용", "party": "국민의힘", "district": "부산진구 제1선거구"},
        {"name": "이대석", "party": "국민의힘", "district": "부산진구 제2선거구"},
        {"name": "김재운", "party": "국민의힘", "district": "부산진구 제3선거구"},
        {"name": "배영숙", "party": "국민의힘", "district": "부산진구 제4선거구"},
        {"name": "윤태한", "party": "국민의힘", "district": "사상구 제1선거구"},
        {"name": "김창석", "party": "국민의힘", "district": "사상구 제2선거구"},
        {"name": "이종환", "party": "국민의힘", "district": "강서구 제1선거구"},
        {"name": "송현준", "party": "국민의힘", "district": "강서구 제2선거구"},
        {"name": "최영진", "party": "국민의힘", "district": "사하구 제1선거구"},
        {"name": "전원석", "party": "더불어민주당", "district": "사하구 제2선거구"},
        {"name": "성창용", "party": "무소속", "district": "사하구 제3선거구"},
        {"name": "이복조", "party": "국민의힘", "district": "사하구 제4선거구"},
        {"name": "송상조", "party": "국민의힘", "district": "서구 제1선거구"},
        {"name": "최도석", "party": "국민의힘", "district": "서구 제2선거구"},
        {"name": "강주택", "party": "국민의힘", "district": "중구 선거구"},
        {"name": "안성민", "party": "국민의힘", "district": "영도구 제1선거구"},
        {"name": "양준모", "party": "국민의힘", "district": "영도구 제2선거구"},
        {"name": "강철호", "party": "국민의힘", "district": "동구 제1선거구"},
        {"name": "황석칠", "party": "국민의힘", "district": "동구 제2선거구"},
        {"name": "조상진", "party": "국민의힘", "district": "남구 제1선거구"},
        {"name": "정태숙", "party": "국민의힘", "district": "남구 제2선거구"},
        {"name": "성현달", "party": "국민의힘", "district": "남구 제3선거구"},
        {"name": "윤일현", "party": "국민의힘", "district": "금정구 제1선거구"},
        {"name": "김광명", "party": "국민의힘", "district": "남구 제4선거구"},
        {"name": "박중묵", "party": "국민의힘", "district": "동래구 제1선거구"},
    ],
    'daegu': [
        {"name": "임인환", "party": "국민의힘", "district": "중구 제1선거구"},
        {"name": "이만규", "party": "국민의힘", "district": "중구 제2선거구"},
        {"name": "김재우", "party": "국민의힘", "district": "동구 제1선거구"},
        {"name": "박소영", "party": "국민의힘", "district": "동구 제2선거구"},
        {"name": "권기훈", "party": "국민의힘", "district": "동구 제3선거구"},
        {"name": "이재숙", "party": "국민의힘", "district": "동구 제4선거구"},
        {"name": "김대현", "party": "국민의힘", "district": "서구 제1선거구"},
        {"name": "이재화", "party": "국민의힘", "district": "서구 제2선거구"},
        {"name": "박우근", "party": "국민의힘", "district": "남구 제1선거구"},
        {"name": "윤영애", "party": "국민의힘", "district": "남구 제2선거구"},
        {"name": "류종우", "party": "국민의힘", "district": "북구 제1선거구"},
        {"name": "김지만", "party": "국민의힘", "district": "북구 제2선거구"},
        {"name": "김재용", "party": "국민의힘", "district": "북구 제3선거구"},
        {"name": "하병문", "party": "국민의힘", "district": "북구 제4선거구"},
        {"name": "이동욱", "party": "국민의힘", "district": "북구 제5선거구"},
        {"name": "정일균", "party": "국민의힘", "district": "수성구 제1선거구"},
        {"name": "조경구", "party": "국민의힘", "district": "수성구 제2선거구"},
        {"name": "이성오", "party": "국민의힘", "district": "수성구 제3선거구"},
        {"name": "전경원", "party": "국민의힘", "district": "수성구 제4선거구"},
        {"name": "김태우", "party": "국민의힘", "district": "수성구 제5선거구"},
        {"name": "이영애", "party": "국민의힘", "district": "달서구 제1선거구"},
        {"name": "허시영", "party": "국민의힘", "district": "달서구 제2선거구"},
        {"name": "황순자", "party": "국민의힘", "district": "달서구 제3선거구"},
        {"name": "이태손", "party": "국민의힘", "district": "달서구 제4선거구"},
        {"name": "윤권근", "party": "국민의힘", "district": "달서구 제5선거구"},
        {"name": "전태선", "party": "국민의힘", "district": "달서구 제6선거구"},
        {"name": "하중환", "party": "국민의힘", "district": "달성군 제1선거구"},
        {"name": "김원규", "party": "국민의힘", "district": "달성군 제2선거구"},
        {"name": "손한국", "party": "국민의힘", "district": "달성군 제3선거구"},
    ],
    'incheon': [
        {"name": "김대중", "party": "국민의힘", "district": "미추홀구 제2선거구"},
        {"name": "김명주", "party": "더불어민주당", "district": "서구 제6선거구"},
        {"name": "김용희", "party": "국민의힘", "district": "연수구 제2선거구"},
        {"name": "김유곤", "party": "국민의힘", "district": "서구 제3선거구"},
        {"name": "김재동", "party": "국민의힘", "district": "미추홀구 제1선거구"},
        {"name": "김종득", "party": "더불어민주당", "district": "계양구 제2선거구"},
        {"name": "나상길", "party": "무소속", "district": "부평구 제4선거구"},
        {"name": "문세종", "party": "더불어민주당", "district": "계양구 제4선거구"},
        {"name": "박종혁", "party": "더불어민주당", "district": "부평구 제6선거구"},
        {"name": "석정규", "party": "더불어민주당", "district": "계양구 제3선거구"},
        {"name": "신동섭", "party": "국민의힘", "district": "남동구 제4선거구"},
        {"name": "신성영", "party": "국민의힘", "district": "중구 제2선거구"},
        {"name": "신영희", "party": "국민의힘", "district": "옹진군 선거구"},
        {"name": "신충식", "party": "무소속", "district": "서구 제4선거구"},
        {"name": "유경희", "party": "더불어민주당", "district": "부평구 제2선거구"},
        {"name": "유승분", "party": "국민의힘", "district": "연수구 제3선거구"},
        {"name": "윤재상", "party": "국민의힘", "district": "강화군 선거구"},
        {"name": "이강구", "party": "국민의힘", "district": "연수구 제5선거구"},
        {"name": "이단비", "party": "국민의힘", "district": "부평구 제3선거구"},
        {"name": "이명규", "party": "국민의힘", "district": "부평구 제1선거구"},
        {"name": "이봉락", "party": "국민의힘", "district": "미추홀구 제3선거구"},
        {"name": "이선옥", "party": "국민의힘", "district": "남동구 제2선거구"},
        {"name": "이순학", "party": "더불어민주당", "district": "서구 제5선거구"},
        {"name": "이오상", "party": "더불어민주당", "district": "남동구 제3선거구"},
        {"name": "이용창", "party": "국민의힘", "district": "서구 제2선거구"},
        {"name": "이인교", "party": "국민의힘", "district": "남동구 제6선거구"},
        {"name": "임관만", "party": "국민의힘", "district": "중구 제1선거구"},
        {"name": "임지훈", "party": "무소속", "district": "부평구 제5선거구"},
        {"name": "임춘원", "party": "국민의힘", "district": "남동구 제1선거구"},
        {"name": "정종혁", "party": "더불어민주당", "district": "서구 제1선거구"},
        {"name": "정해권", "party": "국민의힘", "district": "연수구 제1선거구"},
        {"name": "조성환", "party": "더불어민주당", "district": "계양구 제1선거구"},
        {"name": "조현영", "party": "무소속", "district": "연수구 제4선거구"},
        {"name": "한민수", "party": "국민의힘", "district": "남동구 제5선거구"},
        {"name": "허식", "party": "국민의힘", "district": "동구 선거구"},
        {"name": "김종배", "party": "국민의힘", "district": "미추홀구 제4선거구"},
    ],
    'gwangju': [
        {"name": "홍기월", "party": "더불어민주당", "district": "동구 제1선거구"},
        {"name": "박미정", "party": "더불어민주당", "district": "동구 제2선거구"},
        {"name": "강수훈", "party": "더불어민주당", "district": "서구 제1선거구"},
        {"name": "명진", "party": "더불어민주당", "district": "서구 제2선거구"},
        {"name": "이명노", "party": "더불어민주당", "district": "서구 제3선거구"},
        {"name": "심철의", "party": "더불어민주당", "district": "서구 제4선거구"},
        {"name": "서임석", "party": "더불어민주당", "district": "남구 제1선거구"},
        {"name": "임미란", "party": "더불어민주당", "district": "남구 제2선거구"},
        {"name": "박희율", "party": "더불어민주당", "district": "남구 제3선거구"},
        {"name": "안평환", "party": "더불어민주당", "district": "북구 제1선거구"},
        {"name": "정다은", "party": "더불어민주당", "district": "북구 제2선거구"},
        {"name": "신수정", "party": "더불어민주당", "district": "북구 제3선거구"},
        {"name": "조석호", "party": "더불어민주당", "district": "북구 제4선거구"},
        {"name": "심창욱", "party": "더불어민주당", "district": "북구 제5선거구"},
        {"name": "김나윤", "party": "더불어민주당", "district": "북구 제6선거구"},
        {"name": "최지현", "party": "더불어민주당", "district": "광산구 제1선거구"},
        {"name": "정무창", "party": "더불어민주당", "district": "광산구 제2선거구"},
        {"name": "박필순", "party": "더불어민주당", "district": "광산구 제3선거구"},
        {"name": "이귀순", "party": "더불어민주당", "district": "광산구 제4선거구"},
        {"name": "박수기", "party": "더불어민주당", "district": "광산구 제5선거구"},
    ],
    'daejeon': [
        {"name": "김영삼", "party": "더불어민주당", "district": "서구 제2선거구"},
        {"name": "김진오", "party": "더불어민주당", "district": "서구 제1선거구"},
        {"name": "민경배", "party": "더불어민주당", "district": "중구 제3선거구"},
        {"name": "박종선", "party": "더불어민주당", "district": "유성구 제1선거구"},
        {"name": "박주화", "party": "더불어민주당", "district": "중구 제1선거구"},
        {"name": "방진영", "party": "더불어민주당", "district": "유성구 제2선거구"},
        {"name": "송인석", "party": "더불어민주당", "district": "동구 제1선거구"},
        {"name": "송활섭", "party": "더불어민주당", "district": "대덕구 제2선거구"},
        {"name": "이금선", "party": "더불어민주당", "district": "유성구 제4선거구"},
        {"name": "이병철", "party": "더불어민주당", "district": "서구 제4선거구"},
        {"name": "이상래", "party": "더불어민주당", "district": "동구 제2선거구"},
        {"name": "이재경", "party": "더불어민주당", "district": "서구 제3선거구"},
        {"name": "이중호", "party": "더불어민주당", "district": "서구 제5선거구"},
        {"name": "이한영", "party": "더불어민주당", "district": "서구 제6선거구"},
        {"name": "이효성", "party": "더불어민주당", "district": "대덕구 제1선거구"},
        {"name": "정명국", "party": "더불어민주당", "district": "동구 제3선거구"},
        {"name": "조원휘", "party": "더불어민주당", "district": "유성구 제3선거구"},
        {"name": "이용기", "party": "국민의힘", "district": "대덕구 제3선거구"},
        {"name": "김선광", "party": "국민의힘", "district": "중구 제2선거구"},
    ],
    'ulsan': [
        {"name": "권태호", "party": "국민의힘", "district": "중구 제1선거구"},
        {"name": "김기환", "party": "국민의힘", "district": "중구 제2선거구"},
        {"name": "이성룡", "party": "국민의힘", "district": "중구 제3선거구"},
        {"name": "김종섭", "party": "국민의힘", "district": "중구 제4선거구"},
        {"name": "안수일", "party": "국민의힘", "district": "남구 제1선거구"},
        {"name": "이장걸", "party": "국민의힘", "district": "남구 제2선거구"},
        {"name": "안대룡", "party": "국민의힘", "district": "남구 제3선거구"},
        {"name": "방인섭", "party": "국민의힘", "district": "남구 제4선거구"},
        {"name": "김동칠", "party": "국민의힘", "district": "남구 제5선거구"},
        {"name": "이영해", "party": "국민의힘", "district": "남구 제6선거구"},
        {"name": "김수종", "party": "국민의힘", "district": "동구 제1선거구"},
        {"name": "홍유준", "party": "국민의힘", "district": "동구 제2선거구"},
        {"name": "강대길", "party": "국민의힘", "district": "동구 제3선거구"},
        {"name": "정치락", "party": "국민의힘", "district": "북구 제1선거구"},
        {"name": "문석주", "party": "국민의힘", "district": "북구 제2선거구"},
        {"name": "백현조", "party": "국민의힘", "district": "북구 제3선거구"},
        {"name": "공진혁", "party": "국민의힘", "district": "울주군 제1선거구"},
        {"name": "홍성우", "party": "국민의힘", "district": "울주군 제2선거구"},
        {"name": "김종훈", "party": "국민의힘", "district": "울주군 제3선거구"},
    ],
    'sejong': [
        {"name": "김충식", "party": "국민의힘", "district": "세종시 제1선거구"},
        {"name": "김동빈", "party": "국민의힘", "district": "세종시 제3선거구"},
        {"name": "윤지성", "party": "국민의힘", "district": "세종시 제4선거구"},
        {"name": "김학서", "party": "국민의힘", "district": "세종시 제5선거구"},
        {"name": "안신일", "party": "더불어민주당", "district": "세종시 제6선거구"},
        {"name": "최원석", "party": "국민의힘", "district": "세종시 제7선거구"},
        {"name": "이순열", "party": "더불어민주당", "district": "세종시 제8선거구"},
        {"name": "임채성", "party": "더불어민주당", "district": "세종시 제10선거구"},
        {"name": "이현정", "party": "더불어민주당", "district": "세종시 제11선거구"},
        {"name": "유인호", "party": "더불어민주당", "district": "세종시 제13선거구"},
        {"name": "김현미", "party": "더불어민주당", "district": "세종시 제14선거구"},
        {"name": "김영현", "party": "더불어민주당", "district": "세종시 제15선거구"},
        {"name": "김현옥", "party": "더불어민주당", "district": "세종시 제16선거구"},
        {"name": "김효숙", "party": "더불어민주당", "district": "세종시 제17선거구"},
        {"name": "박란희", "party": "더불어민주당", "district": "세종시 제18선거구"},
        # 세종시 제2, 제9, 제12선거구는 TopoJSON에 없음 (김광운, 김재형 미매칭)
    ],
    'gyeonggi': [
        {"name": "임광현", "party": "국민의힘", "district": "가평군 선거구"},
        {"name": "변재석", "party": "더불어민주당", "district": "고양시 제1선거구"},
        {"name": "이인애", "party": "국민의힘", "district": "고양시 제2선거구"},
        {"name": "정동혁", "party": "더불어민주당", "district": "고양시 제3선거구"},
        {"name": "곽미숙", "party": "국민의힘", "district": "고양시 제6선거구"},
        {"name": "이상원", "party": "국민의힘", "district": "고양시 제7선거구"},
        {"name": "이택수", "party": "국민의힘", "district": "고양시 제8선거구"},
        {"name": "고은정", "party": "더불어민주당", "district": "고양시 제10선거구"},
        {"name": "심홍순", "party": "국민의힘", "district": "고양시 제11선거구"},
        {"name": "김완규", "party": "국민의힘", "district": "고양시 제12선거구"},
        {"name": "김현석", "party": "국민의힘", "district": "과천시 선거구"},
        {"name": "김정호", "party": "국민의힘", "district": "광명시 제1선거구"},
        {"name": "최민", "party": "더불어민주당", "district": "광명시 제2선거구"},
        {"name": "유종상", "party": "더불어민주당", "district": "광명시 제3선거구"},
        {"name": "김용성", "party": "더불어민주당", "district": "광명시 제4선거구"},
        {"name": "유영두", "party": "국민의힘", "district": "광주시 제1선거구"},
        {"name": "임창휘", "party": "더불어민주당", "district": "광주시 제2선거구"},
        {"name": "오창준", "party": "국민의힘", "district": "광주시 제3선거구"},
        {"name": "유형진", "party": "국민의힘", "district": "광주시 제4선거구"},
        {"name": "백현종", "party": "국민의힘", "district": "구리시 제1선거구"},
        {"name": "이은주", "party": "국민의힘", "district": "구리시 제2선거구"},
        {"name": "정윤경", "party": "더불어민주당", "district": "군포시 제1선거구"},
        {"name": "성기황", "party": "더불어민주당", "district": "군포시 제2선거구"},
        {"name": "김미숙", "party": "더불어민주당", "district": "군포시 제3선거구"},
        {"name": "성복임", "party": "더불어민주당", "district": "군포시 제4선거구"},
        {"name": "홍원길", "party": "국민의힘", "district": "김포시 제1선거구"},
        {"name": "오세풍", "party": "국민의힘", "district": "김포시 제2선거구"},
        {"name": "김시용", "party": "국민의힘", "district": "김포시 제3선거구"},
        {"name": "이석균", "party": "국민의힘", "district": "남양주시 제1선거구"},
        {"name": "김미리", "party": "개혁신당", "district": "남양주시 제2선거구"},
        {"name": "조미자", "party": "더불어민주당", "district": "남양주시 제3선거구"},
        {"name": "김동영", "party": "더불어민주당", "district": "남양주시 제4선거구"},
        {"name": "김창식", "party": "더불어민주당", "district": "남양주시 제5선거구"},
        {"name": "유호준", "party": "더불어민주당", "district": "남양주시 제6선거구"},
        {"name": "이병길", "party": "국민의힘", "district": "남양주시 제7선거구"},
        {"name": "임상오", "party": "국민의힘", "district": "동두천시 제2선거구"},
        {"name": "염종현", "party": "더불어민주당", "district": "부천시 제1선거구"},
        {"name": "이선구", "party": "더불어민주당", "district": "부천시 제2선거구"},
        {"name": "이재영", "party": "더불어민주당", "district": "부천시 제3선거구"},
        {"name": "황진희", "party": "더불어민주당", "district": "부천시 제4선거구"},
        {"name": "김광민", "party": "더불어민주당", "district": "부천시 제5선거구"},
        {"name": "김동희", "party": "더불어민주당", "district": "부천시 제6선거구"},
        {"name": "유경현", "party": "더불어민주당", "district": "부천시 제7선거구"},
        {"name": "박상현", "party": "더불어민주당", "district": "부천시 제8선거구"},
        {"name": "문승호", "party": "더불어민주당", "district": "성남시 제1선거구"},
        {"name": "최만식", "party": "더불어민주당", "district": "성남시 제2선거구"},
        {"name": "전석훈", "party": "더불어민주당", "district": "성남시 제3선거구"},
        {"name": "국중범", "party": "더불어민주당", "district": "성남시 제4선거구"},
        {"name": "방성환", "party": "국민의힘", "district": "성남시 제5선거구"},
        {"name": "김진명", "party": "더불어민주당", "district": "성남시 제6선거구"},
        {"name": "안계일", "party": "국민의힘", "district": "성남시 제7선거구"},
        {"name": "이제영", "party": "국민의힘", "district": "성남시 제8선거구"},
        {"name": "남경순", "party": "국민의힘", "district": "수원시 제1선거구"},
        {"name": "박옥분", "party": "더불어민주당", "district": "수원시 제2선거구"},
        {"name": "황대호", "party": "더불어민주당", "district": "수원시 제3선거구"},
        {"name": "장한별", "party": "더불어민주당", "district": "수원시 제4선거구"},
        {"name": "김호겸", "party": "국민의힘", "district": "수원시 제5선거구"},
        {"name": "한원찬", "party": "국민의힘", "district": "수원시 제6선거구"},
        {"name": "최종현", "party": "더불어민주당", "district": "수원시 제7선거구"},
        {"name": "이호동", "party": "국민의힘", "district": "수원시 제8선거구"},
        {"name": "이오수", "party": "국민의힘", "district": "수원시 제9선거구"},
        {"name": "이애형", "party": "국민의힘", "district": "수원시 제10선거구"},
        {"name": "문병근", "party": "국민의힘", "district": "수원시 제11선거구"},
        {"name": "이병숙", "party": "더불어민주당", "district": "수원시 제12선거구"},
        {"name": "안광률", "party": "더불어민주당", "district": "시흥시 제1선거구"},
        {"name": "장대석", "party": "더불어민주당", "district": "시흥시 제2선거구"},
        {"name": "김진경", "party": "더불어민주당", "district": "시흥시 제3선거구"},
        {"name": "김종배", "party": "더불어민주당", "district": "시흥시 제4선거구"},
        {"name": "김동규", "party": "더불어민주당", "district": "안산시 제1선거구"},
        {"name": "김태희", "party": "더불어민주당", "district": "안산시 제2선거구"},
        {"name": "장윤정", "party": "더불어민주당", "district": "안산시 제3선거구"},
        {"name": "강태형", "party": "더불어민주당", "district": "안산시 제5선거구"},
        {"name": "이은미", "party": "더불어민주당", "district": "안산시 제8선거구"},
        {"name": "양운석", "party": "더불어민주당", "district": "안성시 제1선거구"},
        {"name": "김성수", "party": "더불어민주당", "district": "안양시 제1선거구"},
        {"name": "김철현", "party": "국민의힘", "district": "안양시 제2선거구"},
        {"name": "문형근", "party": "더불어민주당", "district": "안양시 제3선거구"},
        {"name": "김재훈", "party": "국민의힘", "district": "안양시 제4선거구"},
        {"name": "유영일", "party": "국민의힘", "district": "안양시 제5선거구"},
        {"name": "이채명", "party": "더불어민주당", "district": "안양시 제6선거구"},
        {"name": "이영주", "party": "국민의힘", "district": "양주시 제1선거구"},
        {"name": "김민호", "party": "국민의힘", "district": "양주시 제2선거구"},
        {"name": "박명숙", "party": "국민의힘", "district": "양평군 제1선거구"},
        {"name": "이혜원", "party": "국민의힘", "district": "양평군 제2선거구"},
        {"name": "서광범", "party": "국민의힘", "district": "여주시 제1선거구"},
        {"name": "김규창", "party": "국민의힘", "district": "여주시 제2선거구"},
        {"name": "윤종영", "party": "국민의힘", "district": "연천군 선거구"},
        {"name": "김영희", "party": "더불어민주당", "district": "오산시 제1선거구"},
        {"name": "조용호", "party": "더불어민주당", "district": "오산시 제2선거구"},
        {"name": "이영희", "party": "국민의힘", "district": "용인시 제1선거구"},
        {"name": "김영민", "party": "국민의힘", "district": "용인시 제2선거구"},
        {"name": "남종섭", "party": "더불어민주당", "district": "용인시 제3선거구"},
        {"name": "전자영", "party": "더불어민주당", "district": "용인시 제4선거구"},
        {"name": "정하용", "party": "국민의힘", "district": "용인시 제5선거구"},
        {"name": "지미연", "party": "국민의힘", "district": "용인시 제6선거구"},
        {"name": "김선희", "party": "국민의힘", "district": "용인시 제7선거구"},
        {"name": "강웅철", "party": "국민의힘", "district": "용인시 제8선거구"},
        {"name": "이성호", "party": "국민의힘", "district": "용인시 제9선거구"},
        {"name": "윤재영", "party": "국민의힘", "district": "용인시 제10선거구"},
        {"name": "김영기", "party": "국민의힘", "district": "의왕시 제1선거구"},
        {"name": "서성란", "party": "국민의힘", "district": "의왕시 제2선거구"},
        {"name": "김정영", "party": "국민의힘", "district": "의정부시 제1선거구"},
        {"name": "이영봉", "party": "더불어민주당", "district": "의정부시 제2선거구"},
        {"name": "최병선", "party": "국민의힘", "district": "의정부시 제3선거구"},
        {"name": "김일중", "party": "국민의힘", "district": "이천시 제1선거구"},
        {"name": "허원", "party": "국민의힘", "district": "이천시 제2선거구"},
        {"name": "고준호", "party": "국민의힘", "district": "파주시 제1선거구"},
        {"name": "조성환", "party": "더불어민주당", "district": "파주시 제2선거구"},
        {"name": "이한국", "party": "국민의힘", "district": "파주시 제4선거구"},
        {"name": "안명규", "party": "국민의힘", "district": "파주시 제5선거구"},
        {"name": "김상곤", "party": "국민의힘", "district": "평택시 제1선거구"},
        {"name": "김재균", "party": "더불어민주당", "district": "평택시 제2선거구"},
        {"name": "윤성근", "party": "국민의힘", "district": "평택시 제4선거구"},
        {"name": "이학수", "party": "국민의힘", "district": "평택시 제5선거구"},
        {"name": "김근용", "party": "국민의힘", "district": "평택시 제6선거구"},
        {"name": "윤충식", "party": "국민의힘", "district": "포천시 제1선거구"},
        {"name": "김성남", "party": "국민의힘", "district": "포천시 제2선거구"},
        {"name": "윤태길", "party": "국민의힘", "district": "하남시 제1선거구"},
        {"name": "김성수", "party": "국민의힘", "district": "하남시 제2선거구"},
        {"name": "오지훈", "party": "더불어민주당", "district": "하남시 제3선거구"},
        {"name": "이홍근", "party": "더불어민주당", "district": "화성시 제1선거구"},
        {"name": "박명원", "party": "개혁신당", "district": "화성시 제2선거구"},
        {"name": "박세원", "party": "무소속", "district": "화성시 제3선거구"},
        {"name": "신미숙", "party": "더불어민주당", "district": "화성시 제4선거구"},
        {"name": "김태형", "party": "더불어민주당", "district": "화성시 제5선거구"},
        {"name": "김회철", "party": "더불어민주당", "district": "화성시 제6선거구"},
        {"name": "이진형", "party": "더불어민주당", "district": "화성시 제7선거구"},
        {"name": "박진영", "party": "더불어민주당", "district": "화성시 제8선거구"},
        {"name": "이을형", "party": "국민의힘", "district": "고양시 제4선거구"},
        {"name": "김경일", "party": "국민의힘", "district": "고양시 제5선거구"},
        {"name": "김민재", "party": "국민의힘", "district": "고양시 제9선거구"},
        {"name": "정태옥", "party": "국민의힘", "district": "김포시 제4선거구"},
        {"name": "김선태", "party": "국민의힘", "district": "동두천시 제1선거구"},
        {"name": "이동현", "party": "더불어민주당", "district": "시흥시 제5선거구"},
        {"name": "정승현", "party": "더불어민주당", "district": "안산시 제4선거구"},
        {"name": "이기환", "party": "더불어민주당", "district": "안산시 제6선거구"},
        {"name": "김철진", "party": "더불어민주당", "district": "안산시 제7선거구"},
        {"name": "박명수", "party": "국민의힘", "district": "안성시 제2선거구"},
        {"name": "정한용", "party": "국민의힘", "district": "의정부시 제4선거구"},
        {"name": "김영환", "party": "국민의힘", "district": "파주시 제3선거구"},
        {"name": "서현옥", "party": "더불어민주당", "district": "평택시 제3선거구"},
    ],
    'chungnam': [
        {"name": "홍성현", "party": "국민의힘", "district": "천안시 제1선거구"},
        {"name": "신한철", "party": "국민의힘", "district": "천안시 제2선거구"},
        {"name": "안종혁", "party": "국민의힘", "district": "천안시 제3선거구"},
        {"name": "구형서", "party": "더불어민주당", "district": "천안시 제4선거구"},
        {"name": "유성재", "party": "국민의힘", "district": "천안시 제5선거구"},
        {"name": "오인철", "party": "더불어민주당", "district": "천안시 제7선거구"},
        {"name": "정병인", "party": "더불어민주당", "district": "천안시 제8선거구"},
        {"name": "박정수", "party": "국민의힘", "district": "천안시 제9선거구"},
        {"name": "김선태", "party": "더불어민주당", "district": "천안시 제10선거구"},
        {"name": "양경모", "party": "국민의힘", "district": "천안시 제11선거구"},
        {"name": "이철수", "party": "국민의힘", "district": "당진시 제1선거구"},
        {"name": "이해선", "party": "국민의힘", "district": "당진시 제2선거구"},
        {"name": "홍기후", "party": "더불어민주당", "district": "당진시 제3선거구"},
        {"name": "이정우", "party": "더불어민주당", "district": "청양군 선거구"},
        {"name": "고광철", "party": "국민의힘", "district": "공주시 제1선거구"},
        {"name": "박기영", "party": "국민의힘", "district": "공주시 제2선거구"},
        {"name": "편삼범", "party": "국민의힘", "district": "보령시 제2선거구"},
        {"name": "오안영", "party": "더불어민주당", "district": "아산시 제1선거구"},
        {"name": "김응규", "party": "국민의힘", "district": "아산시 제2선거구"},
        {"name": "박정식", "party": "국민의힘", "district": "아산시 제3선거구"},
        {"name": "조철기", "party": "더불어민주당", "district": "아산시 제4선거구"},
        {"name": "김옥수", "party": "국민의힘", "district": "서산시 제1선거구"},
        {"name": "이용국", "party": "국민의힘", "district": "서산시 제2선거구"},
        {"name": "이연희", "party": "국민의힘", "district": "서산시 제3선거구"},
        {"name": "윤기형", "party": "국민의힘", "district": "논산시 제1선거구"},
        {"name": "오인환", "party": "더불어민주당", "district": "논산시 제2선거구"},
        {"name": "이재운", "party": "국민의힘", "district": "계룡시 선거구"},
        {"name": "김석곤", "party": "국민의힘", "district": "금산군 제1선거구"},
        {"name": "김복만", "party": "국민의힘", "district": "금산군 제2선거구"},
        {"name": "김기서", "party": "무소속", "district": "부여군 제1선거구"},
        {"name": "조길연", "party": "국민의힘", "district": "부여군 제2선거구"},
        {"name": "전익현", "party": "더불어민주당", "district": "서천군 제1선거구"},
        {"name": "신영호", "party": "국민의힘", "district": "서천군 제2선거구"},
        {"name": "이상근", "party": "국민의힘", "district": "홍성군 제1선거구"},
        {"name": "이종화", "party": "더불어민주당", "district": "홍성군 제2선거구"},
        {"name": "방한일", "party": "국민의힘", "district": "예산군 제1선거구"},
        {"name": "주진하", "party": "국민의힘", "district": "예산군 제2선거구"},
        {"name": "윤희신", "party": "국민의힘", "district": "태안군 제1선거구"},
        {"name": "정광섭", "party": "국민의힘", "district": "태안군 제2선거구"},
        {"name": "최광희", "party": "국민의힘", "district": "보령시 제1선거구"},
        {"name": "안장헌", "party": "더불어민주당", "district": "아산시 제5선거구"},
        {"name": "지민규", "party": "국민의힘", "district": "아산시 제6선거구"},
        {"name": "김도훈", "party": "국민의힘", "district": "천안시 제6선거구"},
    ],
    'chungbuk': [
        {"name": "이동우", "party": "국민의힘", "district": "청주시 제1선거구"},
        {"name": "최정훈", "party": "국민의힘", "district": "청주시 제2선거구"},
        {"name": "김정일", "party": "국민의힘", "district": "청주시 제3선거구"},
        {"name": "박지헌", "party": "국민의힘", "district": "청주시 제4선거구"},
        {"name": "이옥규", "party": "국민의힘", "district": "청주시 제5선거구"},
        {"name": "박재주", "party": "국민의힘", "district": "청주시 제6선거구"},
        {"name": "임병운", "party": "국민의힘", "district": "청주시 제7선거구"},
        {"name": "김성대", "party": "국민의힘", "district": "청주시 제8선거구"},
        {"name": "이욱희", "party": "국민의힘", "district": "청주시 제9선거구"},
        {"name": "박봉순", "party": "국민의힘", "district": "청주시 제10선거구"},
        {"name": "변종오", "party": "더불어민주당", "district": "청주시 제11선거구"},
        {"name": "이의영", "party": "더불어민주당", "district": "청주시 제12선거구"},
        {"name": "황영호", "party": "국민의힘", "district": "청주시 제13선거구"},
        {"name": "김현문", "party": "국민의힘", "district": "청주시 제14선거구"},
        {"name": "조성태", "party": "국민의힘", "district": "충주시 제1선거구"},
        {"name": "이정범", "party": "국민의힘", "district": "충주시 제2선거구"},
        {"name": "이종갑", "party": "국민의힘", "district": "충주시 제3선거구"},
        {"name": "김종필", "party": "국민의힘", "district": "충주시 제4선거구"},
        {"name": "김꽃임", "party": "국민의힘", "district": "제천시 제1선거구"},
        {"name": "김호경", "party": "국민의힘", "district": "제천시 제2선거구"},
        {"name": "박경숙", "party": "국민의힘", "district": "보은군 선거구"},
        {"name": "유재목", "party": "국민의힘", "district": "옥천군 제1선거구"},
        {"name": "박용규", "party": "국민의힘", "district": "옥천군 제2선거구"},
        {"name": "김국기", "party": "국민의힘", "district": "영동군 선거구"},
        {"name": "박병천", "party": "더불어민주당", "district": "증평군 선거구"},
        {"name": "임영은", "party": "더불어민주당", "district": "진천군 제1선거구"},
        {"name": "이양섭", "party": "국민의힘", "district": "진천군 제2선거구"},
        {"name": "이태훈", "party": "국민의힘", "district": "괴산군 선거구"},
        {"name": "이상정", "party": "더불어민주당", "district": "음성군 제1선거구"},
        {"name": "노금식", "party": "국민의힘", "district": "음성군 제2선거구"},
        {"name": "오영탁", "party": "국민의힘", "district": "단양군 선거구"},
    ],
    'gangwon': [
        {"name": "박관희", "party": "국민의힘", "district": "춘천시 제1선거구"},
        {"name": "김희철", "party": "국민의힘", "district": "춘천시 제2선거구"},
        {"name": "박기영", "party": "국민의힘", "district": "춘천시 제3선거구"},
        {"name": "이무철", "party": "국민의힘", "district": "춘천시 제4선거구"},
        {"name": "정재웅", "party": "더불어민주당", "district": "춘천시 제5선거구"},
        {"name": "양숙희", "party": "국민의힘", "district": "춘천시 제6선거구"},
        {"name": "박찬흥", "party": "국민의힘", "district": "춘천시 제7선거구"},
        {"name": "박길선", "party": "국민의힘", "district": "원주시 제1선거구"},
        {"name": "박윤미", "party": "더불어민주당", "district": "원주시 제2선거구"},
        {"name": "김기홍", "party": "국민의힘", "district": "원주시 제3선거구"},
        {"name": "최재민", "party": "국민의힘", "district": "원주시 제4선거구"},
        {"name": "하석균", "party": "국민의힘", "district": "원주시 제5선거구"},
        {"name": "원제용", "party": "국민의힘", "district": "원주시 제6선거구"},
        {"name": "류인출", "party": "더불어민주당", "district": "원주시 제7선거구"},
        {"name": "전찬성", "party": "더불어민주당", "district": "원주시 제8선거구"},
        {"name": "이영욱", "party": "국민의힘", "district": "홍천군 제1선거구"},
        {"name": "홍성기", "party": "국민의힘", "district": "홍천군 제2선거구"},
        {"name": "한창수", "party": "국민의힘", "district": "횡성군 제1선거구"},
        {"name": "최규만", "party": "국민의힘", "district": "횡성군 제2선거구"},
        {"name": "김길수", "party": "국민의힘", "district": "영월군 제1선거구"},
        {"name": "윤길로", "party": "국민의힘", "district": "영월군 제2선거구"},
        {"name": "지광천", "party": "국민의힘", "district": "평창군 제1선거구"},
        {"name": "최종수", "party": "국민의힘", "district": "평창군 제2선거구"},
        {"name": "김기철", "party": "국민의힘", "district": "정선군 선거구"},
        {"name": "김정수", "party": "국민의힘", "district": "철원군 제1선거구"},
        {"name": "엄기호", "party": "국민의힘", "district": "철원군 제2선거구"},
        {"name": "박대현", "party": "국민의힘", "district": "화천군 선거구"},
        {"name": "이기찬", "party": "국민의힘", "district": "양구군 선거구"},
        {"name": "엄윤순", "party": "국민의힘", "district": "인제군 선거구"},
        {"name": "박호균", "party": "국민의힘", "district": "강릉시 제1선거구"},
        {"name": "심오섭", "party": "국민의힘", "district": "강릉시 제2선거구"},
        {"name": "김용래", "party": "국민의힘", "district": "강릉시 제3선거구"},
        {"name": "권혁열", "party": "국민의힘", "district": "강릉시 제4선거구"},
        {"name": "최승순", "party": "국민의힘", "district": "강릉시 제5선거구"},
        {"name": "최재석", "party": "국민의힘", "district": "동해시 제1선거구"},
        {"name": "김기하", "party": "국민의힘", "district": "동해시 제2선거구"},
        {"name": "이한영", "party": "국민의힘", "district": "태백시 제1선거구"},
        {"name": "문관현", "party": "국민의힘", "district": "태백시 제2선거구"},
        {"name": "강정호", "party": "국민의힘", "district": "속초시 제1선거구"},
        {"name": "김시성", "party": "국민의힘", "district": "속초시 제2선거구"},
        {"name": "조성운", "party": "국민의힘", "district": "삼척시 제1선거구"},
        {"name": "심영곤", "party": "국민의힘", "district": "삼척시 제2선거구"},
        {"name": "김용복", "party": "국민의힘", "district": "고성군 선거구"},
        {"name": "진종호", "party": "국민의힘", "district": "양양군 선거구"},
    ],
    'jeonbuk': [
        {"name": "이병도", "party": "더불어민주당", "district": "전주시 제1선거구"},
        {"name": "진형석", "party": "더불어민주당", "district": "전주시 제2선거구"},
        {"name": "송승용", "party": "더불어민주당", "district": "전주시 제3선거구"},
        {"name": "김이재", "party": "더불어민주당", "district": "전주시 제4선거구"},
        {"name": "최형열", "party": "더불어민주당", "district": "전주시 제5선거구"},
        {"name": "김희수", "party": "더불어민주당", "district": "전주시 제6선거구"},
        {"name": "이병철", "party": "더불어민주당", "district": "전주시 제7선거구"},
        {"name": "강동화", "party": "더불어민주당", "district": "전주시 제8선거구"},
        {"name": "서난이", "party": "더불어민주당", "district": "전주시 제9선거구"},
        {"name": "이명연", "party": "더불어민주당", "district": "전주시 제10선거구"},
        {"name": "김명지", "party": "더불어민주당", "district": "전주시 제11선거구"},
        {"name": "국주영은", "party": "더불어민주당", "district": "전주시 제12선거구"},
        {"name": "강태창", "party": "더불어민주당", "district": "군산시 제1선거구"},
        {"name": "김동구", "party": "더불어민주당", "district": "군산시 제2선거구"},
        {"name": "박정희", "party": "더불어민주당", "district": "군산시 제3선거구"},
        {"name": "문승우", "party": "더불어민주당", "district": "군산시 제4선거구"},
        {"name": "김대중", "party": "더불어민주당", "district": "익산시 제1선거구"},
        {"name": "김정수", "party": "더불어민주당", "district": "익산시 제2선거구"},
        {"name": "윤영숙", "party": "더불어민주당", "district": "익산시 제3선거구"},
        {"name": "한정수", "party": "더불어민주당", "district": "익산시 제4선거구"},
        {"name": "임승식", "party": "더불어민주당", "district": "정읍시 제1선거구"},
        {"name": "염영선", "party": "더불어민주당", "district": "정읍시 제2선거구"},
        {"name": "이정린", "party": "더불어민주당", "district": "남원시 제1선거구"},
        {"name": "양해석", "party": "더불어민주당", "district": "남원시 제2선거구"},
        {"name": "나인권", "party": "더불어민주당", "district": "김제시 제1선거구"},
        {"name": "황영석", "party": "더불어민주당", "district": "김제시 제2선거구"},
        {"name": "윤수봉", "party": "더불어민주당", "district": "완주군 제1선거구"},
        {"name": "권요안", "party": "더불어민주당", "district": "완주군 제2선거구"},
        {"name": "전용태", "party": "더불어민주당", "district": "진안군 선거구"},
        {"name": "윤정훈", "party": "더불어민주당", "district": "무주군 선거구"},
        {"name": "박용근", "party": "더불어민주당", "district": "장수군 선거구"},
        {"name": "박정규", "party": "더불어민주당", "district": "임실군 선거구"},
        {"name": "오은미", "party": "진보당", "district": "순창군 선거구"},
        {"name": "김성수", "party": "더불어민주당", "district": "고창군 제1선거구"},
        {"name": "김만기", "party": "더불어민주당", "district": "고창군 제2선거구"},
        {"name": "김정기", "party": "더불어민주당", "district": "부안군 선거구"},
    ],
    'jeonnam': [
        {"name": "최선국", "party": "더불어민주당", "district": "목포시 제1선거구"},
        {"name": "조옥현", "party": "더불어민주당", "district": "목포시 제2선거구"},
        {"name": "박문옥", "party": "더불어민주당", "district": "목포시 제3선거구"},
        {"name": "최정훈", "party": "더불어민주당", "district": "목포시 제4선거구"},
        {"name": "전경선", "party": "더불어민주당", "district": "목포시 제5선거구"},
        {"name": "이광일", "party": "더불어민주당", "district": "여수시 제1선거구"},
        {"name": "서대현", "party": "더불어민주당", "district": "여수시 제2선거구"},
        {"name": "강문성", "party": "더불어민주당", "district": "여수시 제3선거구"},
        {"name": "최무경", "party": "더불어민주당", "district": "여수시 제4선거구"},
        {"name": "최병용", "party": "더불어민주당", "district": "여수시 제5선거구"},
        {"name": "주종섭", "party": "더불어민주당", "district": "여수시 제6선거구"},
        {"name": "정영균", "party": "더불어민주당", "district": "순천시 제1선거구"},
        {"name": "한춘옥", "party": "더불어민주당", "district": "순천시 제2선거구"},
        {"name": "김정희", "party": "더불어민주당", "district": "순천시 제3선거구"},
        {"name": "서동욱", "party": "더불어민주당", "district": "순천시 제4선거구"},
        {"name": "김진남", "party": "더불어민주당", "district": "순천시 제5선거구"},
        {"name": "신민호", "party": "더불어민주당", "district": "순천시 제6선거구"},
        {"name": "한숙경", "party": "더불어민주당", "district": "순천시 제7선거구"},
        {"name": "김정이", "party": "더불어민주당", "district": "순천시 제8선거구"},
        {"name": "김호진", "party": "더불어민주당", "district": "나주시 제1선거구"},
        {"name": "최명수", "party": "더불어민주당", "district": "나주시 제2선거구"},
        {"name": "이재태", "party": "더불어민주당", "district": "나주시 제3선거구"},
        {"name": "임형석", "party": "더불어민주당", "district": "광양시 제1선거구"},
        {"name": "강정일", "party": "더불어민주당", "district": "광양시 제2선거구"},
        {"name": "김태균", "party": "더불어민주당", "district": "광양시 제3선거구"},
        {"name": "박경미", "party": "더불어민주당", "district": "광양시 제4선거구"},
        {"name": "박종원", "party": "더불어민주당", "district": "담양군 제1선거구"},
        {"name": "이규현", "party": "더불어민주당", "district": "담양군 제2선거구"},
        {"name": "진호건", "party": "더불어민주당", "district": "곡성군 선거구"},
        {"name": "이현창", "party": "더불어민주당", "district": "구례군 선거구"},
        {"name": "송형곤", "party": "더불어민주당", "district": "고흥군 제1선거구"},
        {"name": "박선준", "party": "더불어민주당", "district": "고흥군 제2선거구"},
        {"name": "김재철", "party": "더불어민주당", "district": "보성군 제1선거구"},
        {"name": "이동현", "party": "더불어민주당", "district": "보성군 제2선거구"},
        {"name": "임지락", "party": "더불어민주당", "district": "화순군 제1선거구"},
        {"name": "류기준", "party": "더불어민주당", "district": "화순군 제2선거구"},
        {"name": "박형대", "party": "진보당", "district": "장흥군 제1선거구"},
        {"name": "윤명희", "party": "더불어민주당", "district": "장흥군 제2선거구"},
        {"name": "차영수", "party": "더불어민주당", "district": "강진군 선거구"},
        {"name": "김성일", "party": "더불어민주당", "district": "해남군 제1선거구"},
        {"name": "박성재", "party": "무소속", "district": "해남군 제2선거구"},
        {"name": "신승철", "party": "더불어민주당", "district": "영암군 제1선거구"},
        {"name": "손남일", "party": "더불어민주당", "district": "영암군 제2선거구"},
        {"name": "정길수", "party": "더불어민주당", "district": "무안군 제1선거구"},
        {"name": "나광국", "party": "더불어민주당", "district": "무안군 제2선거구"},
        {"name": "모정환", "party": "더불어민주당", "district": "함평군 선거구"},
        {"name": "박원종", "party": "더불어민주당", "district": "영광군 제1선거구"},
        {"name": "오미화", "party": "진보당", "district": "영광군 제2선거구"},
        {"name": "정철", "party": "더불어민주당", "district": "장성군 제1선거구"},
        {"name": "김회식", "party": "더불어민주당", "district": "장성군 제2선거구"},
        {"name": "이철", "party": "더불어민주당", "district": "완도군 제1선거구"},
        {"name": "신의준", "party": "더불어민주당", "district": "완도군 제2선거구"},
        {"name": "김인정", "party": "더불어민주당", "district": "진도군 선거구"},
        {"name": "김문수", "party": "더불어민주당", "district": "신안군 제1선거구"},
        {"name": "최미숙", "party": "더불어민주당", "district": "신안군 제2선거구"},
    ],
    'gyeongbuk': [
        {"name": "한창화", "party": "국민의힘", "district": "포항시 제1선거구"},
        {"name": "김희수", "party": "국민의힘", "district": "포항시 제2선거구"},
        {"name": "이칠구", "party": "국민의힘", "district": "포항시 제3선거구"},
        {"name": "연규식", "party": "국민의힘", "district": "포항시 제4선거구"},
        {"name": "박용선", "party": "국민의힘", "district": "포항시 제5선거구"},
        {"name": "서석영", "party": "국민의힘", "district": "포항시 제6선거구"},
        {"name": "이동업", "party": "국민의힘", "district": "포항시 제7선거구"},
        {"name": "김진엽", "party": "국민의힘", "district": "포항시 제8선거구"},
        {"name": "손희권", "party": "국민의힘", "district": "포항시 제9선거구"},
        {"name": "배진석", "party": "국민의힘", "district": "경주시 제1선거구"},
        {"name": "최덕규", "party": "국민의힘", "district": "경주시 제2선거구"},
        {"name": "최병준", "party": "국민의힘", "district": "경주시 제3선거구"},
        {"name": "박승직", "party": "국민의힘", "district": "경주시 제4선거구"},
        {"name": "최병근", "party": "국민의힘", "district": "김천시 제1선거구"},
        {"name": "이우청", "party": "국민의힘", "district": "김천시 제2선거구"},
        {"name": "조용진", "party": "국민의힘", "district": "김천시 제3선거구"},
        {"name": "김대진", "party": "국민의힘", "district": "안동시 제1선거구"},
        {"name": "권광택", "party": "국민의힘", "district": "안동시 제2선거구"},
        {"name": "김대일", "party": "국민의힘", "district": "안동시 제3선거구"},
        {"name": "김용현", "party": "국민의힘", "district": "구미시 제1선거구"},
        {"name": "황두영", "party": "국민의힘", "district": "구미시 제2선거구"},
        {"name": "허복", "party": "국민의힘", "district": "구미시 제3선거구"},
        {"name": "김상조", "party": "국민의힘", "district": "구미시 제4선거구"},
        {"name": "정근수", "party": "국민의힘", "district": "구미시 제5선거구"},
        {"name": "윤종호", "party": "국민의힘", "district": "구미시 제6선거구"},
        {"name": "김창혁", "party": "국민의힘", "district": "구미시 제7선거구"},
        {"name": "백순창", "party": "국민의힘", "district": "구미시 제8선거구"},
        {"name": "임병하", "party": "국민의힘", "district": "영주시 제1선거구"},
        {"name": "박성만", "party": "국민의힘", "district": "영주시 제2선거구"},
        {"name": "이춘우", "party": "국민의힘", "district": "영천시 제1선거구"},
        {"name": "윤승오", "party": "국민의힘", "district": "영천시 제2선거구"},
        {"name": "남영숙", "party": "국민의힘", "district": "상주시 제1선거구"},
        {"name": "김홍구", "party": "국민의힘", "district": "상주시 제2선거구"},
        {"name": "박영서", "party": "국민의힘", "district": "문경시 제1선거구"},
        {"name": "김창기", "party": "국민의힘", "district": "문경시 제2선거구"},
        {"name": "차주식", "party": "국민의힘", "district": "경산시 제1선거구"},
        {"name": "배한철", "party": "국민의힘", "district": "경산시 제2선거구"},
        {"name": "박채아", "party": "국민의힘", "district": "경산시 제3선거구"},
        {"name": "이철식", "party": "국민의힘", "district": "경산시 제4선거구"},
        # NOTE: 군위군은 2023.7.1 대구 편입. 8회 지선(2022)은 경북 소속이었으나,
        # 9회 지선(2026)부터는 대구 소속. council_members.json에서는 daegu로 이동 완료.
        {"name": "박창석", "party": "국민의힘", "district": "군위군 선거구"},
        {"name": "최태림", "party": "국민의힘", "district": "의성군 제1선거구"},
        {"name": "이충원", "party": "국민의힘", "district": "의성군 제2선거구"},
        {"name": "신효광", "party": "국민의힘", "district": "청송군 선거구"},
        {"name": "박홍열", "party": "무소속", "district": "영양군 선거구"},
        {"name": "황재철", "party": "무소속", "district": "영덕군 선거구"},
        {"name": "이선희", "party": "국민의힘", "district": "청도군 선거구"},
        {"name": "노성환", "party": "국민의힘", "district": "고령군 선거구"},
        {"name": "강만수", "party": "국민의힘", "district": "성주군 선거구"},
        {"name": "정한석", "party": "국민의힘", "district": "칠곡군 제1선거구"},
        {"name": "박순범", "party": "국민의힘", "district": "칠곡군 제2선거구"},
        {"name": "도기욱", "party": "국민의힘", "district": "예천군 제1선거구"},
        {"name": "이형식", "party": "국민의힘", "district": "예천군 제2선거구"},
        {"name": "박창욱", "party": "국민의힘", "district": "봉화군 선거구"},
        {"name": "김원석", "party": "국민의힘", "district": "울진군 선거구"},
        {"name": "남진복", "party": "무소속", "district": "울릉군 선거구"},
    ],
    'gyeongnam': [
        {"name": "서민호", "party": "국민의힘", "district": "창원시 제1선거구"},
        {"name": "백태현", "party": "국민의힘", "district": "창원시 제2선거구"},
        {"name": "박해영", "party": "국민의힘", "district": "창원시 제3선거구"},
        {"name": "박준", "party": "국민의힘", "district": "창원시 제4선거구"},
        {"name": "이찬호", "party": "국민의힘", "district": "창원시 제5선거구"},
        {"name": "이재두", "party": "국민의힘", "district": "창원시 제6선거구"},
        {"name": "박남용", "party": "국민의힘", "district": "창원시 제7선거구"},
        {"name": "강용범", "party": "국민의힘", "district": "창원시 제8선거구"},
        {"name": "정규헌", "party": "국민의힘", "district": "창원시 제9선거구"},
        {"name": "정쌍학", "party": "국민의힘", "district": "창원시 제10선거구"},
        {"name": "진상락", "party": "국민의힘", "district": "창원시 제11선거구"},
        {"name": "이장우", "party": "국민의힘", "district": "창원시 제12선거구"},
        {"name": "조영명", "party": "국민의힘", "district": "창원시 제13선거구"},
        {"name": "박동철", "party": "국민의힘", "district": "창원시 제14선거구"},
        {"name": "박춘덕", "party": "국민의힘", "district": "창원시 제15선거구"},
        {"name": "이치우", "party": "국민의힘", "district": "창원시 제16선거구"},
        {"name": "최학범", "party": "국민의힘", "district": "김해시 제1선거구"},
        {"name": "서희봉", "party": "국민의힘", "district": "김해시 제2선거구"},
        {"name": "최동원", "party": "국민의힘", "district": "김해시 제3선거구"},
        {"name": "권요찬", "party": "국민의힘", "district": "김해시 제4선거구"},
        {"name": "주봉한", "party": "국민의힘", "district": "김해시 제5선거구"},
        {"name": "박병영", "party": "국민의힘", "district": "김해시 제6선거구"},
        {"name": "이시영", "party": "국민의힘", "district": "김해시 제7선거구"},
        {"name": "손덕상", "party": "더불어민주당", "district": "김해시 제8선거구"},
        {"name": "이용식", "party": "국민의힘", "district": "양산시 제1선거구"},
        {"name": "이영수", "party": "국민의힘", "district": "양산시 제2선거구"},
        {"name": "최영호", "party": "국민의힘", "district": "양산시 제3선거구"},
        {"name": "권혁준", "party": "국민의힘", "district": "양산시 제4선거구"},
        {"name": "박인", "party": "국민의힘", "district": "양산시 제5선거구"},
        {"name": "허용복", "party": "국민의힘", "district": "양산시 제6선거구"},
        {"name": "장병국", "party": "국민의힘", "district": "밀양시 제1선거구"},
        {"name": "예상원", "party": "국민의힘", "district": "밀양시 제2선거구"},
        {"name": "정재욱", "party": "국민의힘", "district": "진주시 제1선거구"},
        {"name": "이준부", "party": "더불어민주당", "district": "진주시 제2선거구"},
        {"name": "조현신", "party": "국민의힘", "district": "진주시 제3선거구"},
        {"name": "유계현", "party": "국민의힘", "district": "진주시 제4선거구"},
        {"name": "김진부", "party": "국민의힘", "district": "진주시 제5선거구"},
        {"name": "정수만", "party": "국민의힘", "district": "거제시 제1선거구"},
        {"name": "전기풍", "party": "국민의힘", "district": "거제시 제2선거구"},
        {"name": "윤준영", "party": "국민의힘", "district": "거제시 제3선거구"},
        {"name": "강성중", "party": "국민의힘", "district": "통영시 제1선거구"},
        {"name": "김태규", "party": "국민의힘", "district": "통영시 제2선거구"},
        {"name": "임철규", "party": "국민의힘", "district": "사천시 제1선거구"},
        {"name": "김현철", "party": "국민의힘", "district": "사천시 제2선거구"},
        {"name": "권원만", "party": "국민의힘", "district": "의령군 선거구"},
        {"name": "조영제", "party": "국민의힘", "district": "함안군 제1선거구"},
        {"name": "조인제", "party": "국민의힘", "district": "함안군 제2선거구"},
        {"name": "성낙인", "party": "국민의힘", "district": "창녕군 제1선거구"},
        {"name": "우기수", "party": "국민의힘", "district": "창녕군 제2선거구"},
        {"name": "백수명", "party": "국민의힘", "district": "고성군 제1선거구"},
        {"name": "허동원", "party": "국민의힘", "district": "고성군 제2선거구"},
        {"name": "류경완", "party": "더불어민주당", "district": "남해군 선거구"},
        {"name": "김구연", "party": "국민의힘", "district": "하동군 선거구"},
        {"name": "신종철", "party": "국민의힘", "district": "산청군 선거구"},
        {"name": "김재웅", "party": "국민의힘", "district": "함양군 선거구"},
        {"name": "박주언", "party": "국민의힘", "district": "거창군 제1선거구"},
        {"name": "김일수", "party": "국민의힘", "district": "거창군 제2선거구"},
        {"name": "장진영", "party": "국민의힘", "district": "합천군 선거구"},
    ],
    'jeju': [
        # 제주시 동 지역
        {"name": "한권", "party": "더불어민주당", "district": "제주시 제1선거구"},
        {"name": "박호형", "party": "더불어민주당", "district": "제주시 제2선거구"},
        {"name": "김기환", "party": "더불어민주당", "district": "제주시 제3·4선거구"},    # 이도2동갑
        {"name": "한동수", "party": "더불어민주당", "district": "제주시 제3·4선거구"},    # 이도2동을
        {"name": "정민구", "party": "더불어민주당", "district": "제주시 제5선거구"},
        {"name": "김황국", "party": "국민의힘", "district": "제주시 제6선거구"},
        {"name": "강성의", "party": "더불어민주당", "district": "제주시 제7선거구"},
        {"name": "김경미", "party": "더불어민주당", "district": "제주시 제8선거구"},
        {"name": "홍인숙", "party": "더불어민주당", "district": "제주시 제9·10선거구"},   # 아라동갑
        {"name": "강경흠", "party": "더불어민주당", "district": "제주시 제9·10선거구"},   # 아라동을
        {"name": "이승아", "party": "더불어민주당", "district": "제주시 제11선거구"},
        {"name": "양영식", "party": "더불어민주당", "district": "제주시 제12·13선거구"},  # 연동갑
        {"name": "강철남", "party": "더불어민주당", "district": "제주시 제12·13선거구"},  # 연동을
        {"name": "양경호", "party": "더불어민주당", "district": "제주시 제14·15선거구"},  # 노형동갑
        {"name": "이상봉", "party": "더불어민주당", "district": "제주시 제14·15선거구"},  # 노형동을
        {"name": "송창권", "party": "더불어민주당", "district": "제주시 제16선거구"},
        # 제주시 읍면 지역
        {"name": "양용만", "party": "국민의힘", "district": "제주시 제17선거구"},
        {"name": "고태민", "party": "국민의힘", "district": "제주시 제18·19선거구"},      # 애월읍갑
        {"name": "강봉직", "party": "더불어민주당", "district": "제주시 제18·19선거구"},  # 애월읍을
        {"name": "김경학", "party": "더불어민주당", "district": "제주시 제20선거구"},
        {"name": "현길호", "party": "더불어민주당", "district": "제주시 제21선거구"},
        {"name": "김승준", "party": "더불어민주당", "district": "제주시 제22선거구"},
        # 서귀포시 동 지역
        {"name": "강충룡", "party": "국민의힘", "district": "서귀포시 제1선거구"},
        {"name": "강상수", "party": "국민의힘", "district": "서귀포시 제2선거구"},
        {"name": "김대진", "party": "더불어민주당", "district": "서귀포시 제3선거구"},
        {"name": "이정엽", "party": "국민의힘", "district": "서귀포시 제4선거구"},
        {"name": "임정은", "party": "더불어민주당", "district": "서귀포시 제5선거구"},
        # 서귀포시 읍면 지역
        {"name": "양병우", "party": "무소속", "district": "서귀포시 제6선거구"},
        {"name": "송영훈", "party": "더불어민주당", "district": "서귀포시 제7선거구"},
        {"name": "현기종", "party": "국민의힘", "district": "서귀포시 제8선거구"},
        {"name": "하성용", "party": "더불어민주당", "district": "서귀포시 제9선거구"},
        {"name": "강연호", "party": "국민의힘", "district": "서귀포시 제10선거구"},
    ],
}


def build():
    output = {
        '_meta': {
            'description': '광역의원 현직의원 데이터 (2022 지방선거 당선인 기준)',
            'source': '각 시도의회 홈페이지 + 나무위키',
            'electionName': '제8회 전국동시지방선거 (2022.06.01)',
            'generatedAt': datetime.now().isoformat(),
        },
        'regions': {}
    }

    total_matched = 0
    total_unmatched = 0

    for region_key, members in RAW_DATA.items():
        topo_districts = load_topo_districts(region_key)
        print(f'\n[{region_key}] TopoJSON: {len(topo_districts)}개, 수집: {len(members)}명')

        district_members = {}
        unmatched = []

        for m in members:
            matched = match_district(m['district'], topo_districts)
            if matched:
                if matched not in district_members:
                    district_members[matched] = []
                district_members[matched].append({
                    'name': m['name'],
                    'party': normalize_party(m['party']),
                    'partyName': m['party'],
                })
            else:
                unmatched.append(m)

        if unmatched:
            print(f'  ⚠️  미매칭 {len(unmatched)}명:')
            for u in unmatched[:10]:
                print(f'     {u["district"]} - {u["name"]}')

        output['regions'][region_key] = {
            'districtMembers': district_members,
            'totalMembers': sum(len(v) for v in district_members.values()),
            'totalDistricts': len(district_members),
        }

        total_matched += sum(len(v) for v in district_members.values())
        total_unmatched += len(unmatched)
        print(f'  ✅ {output["regions"][region_key]["totalMembers"]}명 매칭 / {len(district_members)}개 선거구')

    output['_meta']['totalMembers'] = total_matched
    output['_meta']['unmatchedMembers'] = total_unmatched

    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f'\n💾 저장: {OUTPUT_FILE}')
    print(f'   총 {total_matched}명 매칭, {total_unmatched}명 미매칭')


if __name__ == '__main__':
    build()
